### ISSUE TITLE
availableProcessors has to be more than 1

### ISSUE THREAD

**Issue by MoaufmKlo** [itzg/docker-bungeecord#22]
I've tried using the image in docker-compose, though when starting the following comes up:

```
14:32:00 [SEVERE] Exception in thread "main"
14:32:00 [SEVERE] java.lang.ExceptionInInitializerError
14:32:00 [SEVERE]     at net.md_5.bungee.netty.PipelineUtils.newEventLoopGroup(PipelineUtils.java:123)
14:32:00 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
14:32:00 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
14:32:00 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
14:32:00 [SEVERE] Caused by: java.lang.IllegalArgumentException: availableProcessors: 0 (expected: > 0)
14:32:00 [SEVERE]     at io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:44)
14:32:00 [SEVERE]     at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44)
14:32:00 [SEVERE]     at io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70)
14:32:00 [SEVERE]     at io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98)
14:32:00 [SEVERE]     at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:41)
14:32:00 [SEVERE]     ... 4 more
```

docker-compose.yml:
```
version: '3.8'

services:
  lobby:
    image: itzg/minecraft-server:adopt11
    volumes:
      - ./lobby:/data
    environment:
      - TYPE=SPIGOT
      - VERSION=Spigot-1.8.8-R0.1-SNAPSHOT-latest
      - EULA=TRUE
      - ONLINE_MODE=FALSE
    restart: always
  bungeecord:
    image: itzg/bungeecord
    ports:
     - 25565:25577
#    environment:
#      - MEMORY=1028m
    volumes:
      - ./bungeecord:/server
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
```

Thanks in advance :)

**Comment by itzg** [comment]
I’m sorry, I’m not familiar with that error. You may want to ask in the bungeecord repo.

**Comment by MoaufmKlo** [comment]
Alright, thank you. :)
