### ISSUE TITLE
Download failed after setting UID to 1001

### ISSUE THREAD

**Issue by cloudwithax** [itzg/docker-bungeecord#99]
Trying to start up this docker image and setting the user ID variable fails:

```
$ docker run -it -u 1001 -v /bungee:/server -p 25565:25577 itzg/bungeecord
[init] Resolving type given BUNGEECORD
[init] Downloading https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
[mc-image-helper] 23:06:05.063 ERROR : Operation failed: /server/BungeeCord-lastStableBuild.jar
ERROR: failed to download
```

**Comment by cloudwithax** [comment]
Still experiencing the same issue

**Comment by itzg** [comment]
...oh, you could ask on the Discord server if anyone is running with SElinux enabled. 

Also, I seem to remember a permissive mode that can be enabled to know what security rules would satisfy SElinux.

**Comment by cloudwithax** [comment]
I'm not using SELinux, I'm running this off of an Ubuntu VM

**Comment by itzg** [comment]
I'm so sorry, I commented on the wrong issue. I'm juggling a similar sounding issue over in the java server repo.

In yours, I need to lookup why the error log was so vague.

**Comment by cloudwithax** [comment]
Yeah I was wondering that as well. Is there  anyway I can turn on verbose logging within the container, or does no such option exist?

**Comment by itzg** [comment]
Good question. Yes, set `-e DEBUG_GET=true`

**Comment by cloudwithax** [comment]
Alright, after turning debug mode on, this is what happens:

```
$ docker run -it -u 1001 -e DEBUG_GET=true -v ~/bungee:/server  -p 25565:25577 itzg/bungeecord
[init] Resolving type given BUNGEECORD
[init] Downloading https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
[mc-image-helper] 20:17:39.240 DEBUG : Getting uri=https://ci.md-5.net/job/Bunge                        eCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
[mc-image-helper] 20:17:39.250 DEBUG : Intercepting request uri=https://ci.md-5.                        net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
[mc-image-helper] 20:17:39.506 DEBUG : Post-request capturing redirectLocations=[]
[mc-image-helper] 20:17:39.904 ERROR : Operation failed: /server/BungeeCord-lastStableBuild.jar
[mc-image-helper] 20:17:39.906 DEBUG : Details
java.nio.file.AccessDeniedException: /server/BungeeCord-lastStableBuild.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at me.itzg.helpers.get.SaveToFileHandler.handleEntity(SaveToFileHandler.java:24)
        at me.itzg.helpers.get.SaveToFileHandler.handleEntity(SaveToFileHandler.java:11)
        at org.apache.hc.client5.http.impl.classic.AbstractHttpClientResponseHan                        dler.handleResponse(AbstractHttpClientResponseHandler.java:70)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:202)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:143)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:117)
        at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:381)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:182)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSame                        Parent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:46)
ERROR: failed to download
```

**Comment by itzg** [comment]
It's a file/directory permission issue then. You'll need to investigate that further.
